### ISSUE TITLE
"name not defined" error at launch

### ISSUE THREAD

**Issue by edogawa23** [Slimbook-Team/slimbookamdcontroller#30]
This is the error and python traceback I get (trying both from source directory and my installed rpm binary, via terminal):

> Traceback (most recent call last):
  File "/usr/bin/slimbookamdcontroller", line 35, in <module>
    from slimbookamdcontroller import SlimbookAMD
  File "/usr/share/slimbookamdcontroller/src/slimbookamdcontroller.py", line 6, in <module>
    from sections.gpu_section import GpuSection
  File "/usr/share/slimbookamdcontroller/src/sections/gpu_section.py", line 21, in <module>
    class GpuSection():
  File "/usr/share/slimbookamdcontroller/src/sections/gpu_section.py", line 150, in GpuSection
    def __render_chart(self, gpu: GpuService) -> FigureCanvas:
NameError: name 'GpuService' is not defined

Interestingly, if my memory doesn't play tricks, I was able to run it on my older ASUS i5 laptop, back when creating/testing the rpm ... I'll check that again soon, right now I'm short of time

**Comment by katsuja** [comment]
Instead, I get the following error:
$slimbookamdcontroller
/usr/share/slimbookamdcontroller/src
Traceback (most recent call last):
  File "/usr/bin/slimbookamdcontroller", line 35, in <module>
    from slimbookamdcontroller import SlimbookAMD
  File "/usr/share/slimbookamdcontroller/src/slimbookamdcontroller.py", line 34, in <module>
    type = patron.search(cpu).group(1).strip()
           ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

OS: Arch Linux x86_64 
Host: Surface Laptop 4 124I:00055T:000M:0200000B
Kernel: Linux 6.3.4-arch1-1-surface
GPU Driver: amdgpu 
CPU: AMD Ryzen 5 Microsoft Surface Edition (12)
GPU: AMD ATI 03:00.0 Renoir

**Comment by MarSlimbook** [comment]
Hi @katsuja does this command work in your os?

> cat /proc/cpuinfo | grep name | uniq

**Comment by MarSlimbook** [comment]
@edogawa23 I think it's not importing class GpuService correctly, but I'm not sure why, here is the line:
https://github.com/Slimbook-Team/slimbookamdcontroller/blob/bea20f4de267855315cae7c0724fe6a690dd961f/src/sections/gpu_section.py#L15

To make sure this is the error, you can edit that try / except this way:
```
try:
    from services.gpu_service import GpuService
except NameError:
    print(NameError)
    pass
```
If when you init the app (via terminal) the error is printed, tell me, and maybe check src/services/gpu_service.py file and directory's permissions.
PD: Thank you so much for building RPM packages of our apps!

**Comment by edogawa23** [comment]
Aha, this clears it up, the error printed is this:

> Traceback (most recent call last):
  File "/home/ed/src/slimbookamdcontroller/src/slimbookamdcontroller.py", line 6, in <module>
    from sections.gpu_section import GpuSection
  File "/home/ed/src/slimbookamdcontroller/src/sections/gpu_section.py", line 15, in <module>
    from services.gpu_service import GpuService
  File "/home/ed/src/slimbookamdcontroller/src/services/gpu_service.py", line 1, in <module>
    import pyamdgpuinfo
ModuleNotFoundError: No module named 'pyamdgpuinfo'

After installing this via "pip install pyamdgpuinfo", The GUI launches.
This is not available from any OBS (distro, community or 3rdparty) repos for openSUSE.
So ideally, I'll build a package of this as well, to have all the runtime dependencies available from the package manager.

Not sure when I  will find time to do that, though.

**Comment by edogawa23** [comment]
Testing the app now, I see ryzenadj needs to be installed, which is missing in any "official" openSUSE distro but available in OBS "hardware" community repo. I'll see what I can do to get it included in the distro along with slimbook apps, once I'm happy with my packaging.

**Comment by katsuja** [comment]
> Hi @katsuja does this command work in your os?
> 
> > cat /proc/cpuinfo | grep name | uniq


Hi @katsuja does this command work in your os?

    cat /proc/cpuinfo | grep name | uniq

Hi.
cat /proc/cpuinfo | grep name | uniq
model name	: AMD Ryzen 5 Microsoft Surface (R) Edition

**Comment by katsuja** [comment]
> Hi @katsuja does this command work in your os?
> 
> > cat /proc/cpuinfo | grep name | uniq

Hi @MarSlimbook 
cat /proc/cpuinfo | grep name | uniq
model name : AMD Ryzen 5 Microsoft Surface (R) Edition

**Comment by slimbook** [comment]
> So ideally, I'll build a package of this as well, to have all the runtime dependencies available from the package manager.

Awesome! 
We could also build a .deb package of this python package to add it as a dependency in the control file some day.

**Comment by slimbook** [comment]
> model name : AMD Ryzen 5 Microsoft Surface (R) Edition

Some changes should be made to the app to support this kind of processor name, it's unsupported for the time being...
As I've seen in the specifications it might be an:

> AMD Ryzen 5 4680U Mobile Processor with Radeon™ Graphics Microsoft Surface Edition (6 cores)

We usually set parameters based on cpu power suffix, we should do some research to add this kind of processors.

**Comment by edogawa23** [comment]
> Interestingly, if my memory doesn't play tricks, I was able to run it on my older ASUS i5 laptop, back when creating/testing the rpm ... I'll check that again soon, right now I'm short of time

oh I checked and of course, on that laptop, it was slimbookintelcontroller that I had got running...

**Comment by jcarolinares** [comment]
Hello, same error

Ubuntu distributio, the original one from Slimbook I must say, Slimbook Titan

```shell
jcarolinares@jcarolinares-TITAN:~$ slimbookamdcontroller
/usr/share/slimbookamdcontroller/src
Traceback (most recent call last):
  File "/usr/bin/slimbookamdcontroller", line 35, in <module>
    from slimbookamdcontroller import SlimbookAMD
  File "/usr/share/slimbookamdcontroller/src/slimbookamdcontroller.py", line 6, in <module>
    from sections.gpu_section import GpuSection
  File "/usr/share/slimbookamdcontroller/src/sections/gpu_section.py", line 21, in <module>
    class GpuSection():
  File "/usr/share/slimbookamdcontroller/src/sections/gpu_section.py", line 150, in GpuSection
    def __render_chart(self, gpu: GpuService) -> FigureCanvas:
NameError: name 'GpuService' is not defined

``` 

It would be great to know the reason and have some patch if possible

**Comment by jcarolinares** [comment]
> Hello, same error
> 
> Ubuntu distributio, the original one from Slimbook I must say, Slimbook Titan
> 
> ```shell
> jcarolinares@jcarolinares-TITAN:~$ slimbookamdcontroller
> /usr/share/slimbookamdcontroller/src
> Traceback (most recent call last):
>   File "/usr/bin/slimbookamdcontroller", line 35, in <module>
>     from slimbookamdcontroller import SlimbookAMD
>   File "/usr/share/slimbookamdcontroller/src/slimbookamdcontroller.py", line 6, in <module>
>     from sections.gpu_section import GpuSection
>   File "/usr/share/slimbookamdcontroller/src/sections/gpu_section.py", line 21, in <module>
>     class GpuSection():
>   File "/usr/share/slimbookamdcontroller/src/sections/gpu_section.py", line 150, in GpuSection
>     def __render_chart(self, gpu: GpuService) -> FigureCanvas:
> NameError: name 'GpuService' is not defined
> ```
> 
> It would be great to know the reason and have some patch if possible

Additional info

Partial solution from @edogawa23 works in my slimbook titan:

```shell
pip install pyamdgpuinfo
``` 
would be great to add the dependency to the installer
